### ISSUE TITLE
stability and usage

### ISSUE THREAD

**Issue by Efreak** [viraptor/libremotec#1]
Is this stable, and would it work properly if bash was run this way to mount filesystems for other programs?

I've been looking for something like this to use on Android, inside Termux, to get around the inability to mount remote filesystems. Things I'm interested in: git, minidlna, external storage of files for apt. Better yet if the server works with Windows (using WSL1, Cygwin, or msys2; I prefer not to run a full VM)

**Comment by viraptor** [comment]
This repo is a circus trick. It's never going to be stable or a good idea :-)
